# Generated by Django 5.1.4 on 2024-12-29 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mailing_list_mngr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mailinglist",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Владелец",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="attempttosend",
            name="mailing_list",
            field=models.ForeignKey(
                blank=True,
                help_text="Рассылка",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mailing_list_mngr.mailinglist",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Владелец",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="mailinglist",
            name="message",
            field=models.ForeignKey(
                blank=True,
                help_text="Сообщение рассылки",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mailing_list_mngr.message",
                verbose_name="Сообщение рассылки",
            ),
        ),
        migrations.AddField(
            model_name="recipient",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Владелец",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="mailinglist",
            name="recipients",
            field=models.ForeignKey(
                blank=True,
                help_text="Получатели рассылки",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mailing_list_mngr.recipient",
                verbose_name="Получатели рассылки",
            ),
        ),
    ]
