# Generated by Django 5.1.4 on 2025-01-01 22:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mailing_list_mngr", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="description",
            new_name="body",
        ),
    ]
