# Generated by Django 5.1.4 on 2025-01-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing_list_mngr", "0003_rename_description_message_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipient",
            old_name="message",
            new_name="comments",
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(blank=True, null=True, verbose_name="Текст письма"),
        ),
    ]
