# Generated by Django 5.1.4 on 2025-01-06 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "mailing_list_mngr",
            "0004_rename_message_recipient_comments_alter_message_body",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempttosend",
            name="mailing_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mailing_list_mngr.mailinglist",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AlterField(
            model_name="mailinglist",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mailing_list_mngr.message",
                verbose_name="Сообщение рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailinglist",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.RemoveField(
            model_name="mailinglist",
            name="recipients",
        ),
        migrations.AlterField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="mailinglist",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="mailing_list_mngr.recipient",
                verbose_name="Получатели рассылки",
            ),
        ),
    ]
