# Generated by Django 5.1.4 on 2025-01-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing_list_mngr", "0005_alter_attempttosend_mailing_list_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglist",
            name="finished_at",
            field=models.DateTimeField(
                blank=True,
                help_text="формат d.m.Y H:M",
                null=True,
                verbose_name="Дата и время окончания отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailinglist",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="формат d.m.Y H:M",
                null=True,
                verbose_name="Дата и время начала отправки",
            ),
        ),
    ]
