# Generated by Django 5.1.4 on 2025-01-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing_list_mngr", "0006_alter_mailinglist_finished_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attempttosend",
            name="header",
        ),
        migrations.AddField(
            model_name="attempttosend",
            name="server_response",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ сервера"),
        ),
        migrations.AlterField(
            model_name="attempttosend",
            name="status",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Статус попытки рассылки",
            ),
        ),
    ]
