# Generated by Django 5.1.4 on 2025-01-14 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing_list_mngr", "0007_remove_attempttosend_header_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempttosend",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mailing_list_mngr.recipient",
                verbose_name="Получатель письма",
            ),
        ),
    ]
