# Generated by Django 5.1.4 on 2025-01-19 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mailing_list_mngr", "0008_attempttosend_recipient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailinglist",
            options={
                "permissions": [("can_stop_mailingList", "can stop mailingList")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Письмо", "verbose_name_plural": "Письма"},
        ),
    ]
