# Generated by Django 5.1.4 on 2025-01-19 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mailing_list_mngr", "0009_alter_mailinglist_options_alter_message_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailinglist",
            options={
                "permissions": [
                    ("can_stop_mailingList", "can stop mailingList"),
                    ("can_send_mailingList", "can send mailingList"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
