# Generated by Django 5.1.4 on 2025-01-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing_list_mngr", "0010_alter_mailinglist_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglist",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                to="mailing_list_mngr.recipient",
                verbose_name="Получатели рассылки",
            ),
        ),
    ]
